_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  DISTILLER:
    MODEL_LOAD_OFFICIAL: True
    MODEL_DISTILLER_CONFIG: 'COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml'

    INS:
      INPUT_FEATS: ['p2', 'p3', 'p4', 'p5', 'p6']
      MAX_LABELS: 100

    INS_ATT_MIMIC:
      WEIGHT_VALUE: 3.0
      
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CLIP_GRADIENTS: {"ENABLED": True}
