_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: FCOS
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
