_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: FCOSBase
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEFORM_MODULATED: True
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
