_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: POTO
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    NMS_THRESH_TEST: 1.0
  NMS_TYPE: 'null'
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
